import mongoose from "mongoose";

const solicitudesSchema=new mongoose.Schema({
    consecutivo:{type:String},
    idUsuario: {type: mongoose.Schema.Types.ObjectId, ref: 'Usuario', required: true },
    tipodeOperacion:{type:String,required:true},
    empresa:{type:String,required:true},
    fechaInicio:{type:Date,required:true},
    horaInicio:{type:Date,required:true},
    fechaFin:{type:Date,required:true},
    horaFin:{type:Date,required:true},
    detalles_cronograma:{type:String},
    peso_maximo:{type:String},
    municipio:{type:String,required:true},
    departamento:{type:String,required:true},
    tipodecontactovisualconlaua:{type:String,required:true},
    vueloespecial:{type:String,required:true},
    justificacionvueloespecial:{type:String},
    poligononombre:{type:String},
    altura_poligono:{type:String},
    latitud_poligono_1:{type:String},
    longitud_poligono_1:{type:String},
    latitud_poligono_2:{type:String},
    longitud_poligono_2:{type:String},
    latitud_poligono_3:{type:String},
    longitud_poligono_3:{type:String},
    latitud_poligono_4:{type:String},
    longitud_poligono_4:{type:String},
    latitud_poligono_5:{type:String},
    longitud_poligono_5:{type:String},
    tramolinealnombre:{type:String},
    altura_tramo:{type:String},
    latitud_tramo_1:{type:String},
    longitud_tramo_1:{type:String},
    latitud_tramo_2:{type:String},
    longitud_tramo_2:{type:String},
    latitud_tramo_3:{type:String},
    longitud_tramo_3:{type:String},
    latitud_tramo_4:{type:String},
    longitud_tramo_4:{type:String},
    latitud_tramo_5:{type:String},
    longitud_tramo_5:{type:String},
    circuferenciaencoordenadayradionombre:{type:String},
    altura_circunferencia:{type:String},
    latitud_circunferencia_1:{type:String},
    longitud_circunferencia_1:{type:String},
    check_kmz:{type:String},
    Link:{type:String},
    Estado:{type:String},
    fechadeCreacion:{type:String,default: Date.now()},
    Realizado:{type:String},

})

export default mongoose.model("Solicitud",solicitudesSchema)


